module.exports = {

app : {
    user : '👤',
    users : '👥',
    gear : '⚙️',
    lock : '🔒',
    'open-lock' : '🔓',
    key : '🔑',
    home : '🏠',
    exit : '🚪',
    call : '📞',
    search : '🔍',
    battery : '🔋',
    'power-plug' : '🔌',
    alarm : '🔔',
    'volume-min' : '🔈',
    'volume-mid' : '🔉',
    'volume-max' : '🔊',
    'dim' : '🔅',
    'bright' : '🔆',
    access : '♿',
    bars : '☰',
    'h-dots' : '⋯',
    'v-dots' : '⋮',
    rows : '▤',
    columns : '▥',
    grid : '▦',
    'spaced-grid' : '𝍖',
    warning : '⚠',
    error : '⨂',
    ban : '🛇',
    mute : '🔇',
    'alarm-off' : '🔕',
},

office : {
    file : '📄',
    file2 : '🖻',
    file3 : '🖺',
    folder : '📂',
    edit : '✏️',
    pen : '🖊️',
    pen2 : '🖋️',
    paintbrush : '🖌️',
    cut : '✂️',
    clip : '📎',
    clipboard : '📋',
    link : '🔗',
    ruler : '📏',
    pin : '📌',
    'safety-pin' : '🧷',
    card : '💳',
    label : '🏷️',
    memo : '📝',
    scroll : '📜',
    book : '📕',
    books : '📚',
    bookmark : '🔖',
    'open-book' : '📖',
    notebook : '📓',
    notepad : '🗒️',
    calendar : '📅',
    envelope : '✉️',
    email : '📧',
    mailbox : '📫',
    package : '📦',
    briefcase : '💼',
    newspaper : '📰',
    cabinet : '🗄️',
    'trash-can' : '🗑️',
},

electronics : {
    laptop : '💻',
    desktop : '🖥️',
    keyboard : '⌨️',
    'pc-mouse' : '🖱️',
    printer : '🖨️',
    smartphone : '📱',
    telephone : '☎️',
    microphone : '🎤',
    'studio-mic' : '🎙️',
    headphones : '🎧',
    camera : '📷',
    'video-camera' : '📹',
    'movie-camera' : '🎥',
    projector : '📽️',
    tv : '📺',
    radio : '📻',
    stereo : '📾',
    loudspeaker : '📢',
    gamepad : '🎮',
    joystick : '🕹️',
    'sd-card' : '⛘',
    cd : '💿',
    minidisc : '💽',
    floppy : '💾',
    tape : '📼',
},

tools : {
    wrench : '🔧',
    hammer : '🔨',
    pick : '⛏️',
    tools : '🛠️',
    tools2 : '⚒️',
    toolbox : '🧰',
    clamp : '🗜️',
    bolt : '🔩',
    anchor : '⚓',
    scales : '⚖️',
    'old-key' : '🗝️',
    map : '🗺️',
    compass : '🧭',
    magnet : '🧲',
    abacus : '🧮',
    bulb : '💡',
    flashlight : '🔦',
    microscope : '🔬',
    telescope : '🔭',
    antenna : '📡',
    satellite : '🛰️',
    watch : '⌚',
    stopwatch : '⏱️',
    clock : '⏰',
    hourglass : '⌛',
    dagger : '🗡️',
    swords : '⚔️',
    shield : '🛡️',
    bow : '🏹',
    gun : '🔫',
},

vehicles : {
    skate : '🛹',
    scooter : '🛴',
    bicycle : '🚲',
    motorscooter : '🛵',
    motorcycle : '🏍️',
    car : '🚗',
    'race-car' : '🏎️',
    rv : '🚙',
    bus : '🚌',
    minibus : '🚐',
    truck : '🚚',
    ambulance : '🚑',
    'fire-engine' : '🚒',
    metro : '🚇',
    train : '🚄',
    locomotive : '🚂',
    canoe : '🛶',
    sailboat : '⛵',
    speedboat : '🚤',
    motorboat : '🛥️',
    ferry : '⛴️',
    ship : '🚢',
    plane : '✈️',
    'small-plane': '🛩️',
    helicopter : '🚁',
    rocket : '🚀',
    ufo : '🛸',
},

faces : {
    man : '👨',
    woman : '👩',
    prince : '🤴',
    princess : '👸',
    robot : '🤖',
    skull : '💀',
    imp : '👿',
    monster : '👾',
    alien : '👽',
    ghost : '👻',
    goblin : '👺',
    ogre : '👹',
},

characters : {
    teacher : '👨‍🏫',
    teacherw : '👩‍🏫',
    scientist : '👨‍🔬',
    scientistw : '👩‍🔬',
    hacker : '👨‍💻',
    hackerw : '👩‍💻',
    artist : '👨‍🎨',
    artistw : '👩‍🎨',
    doctor : '👨‍⚕️',
    doctorw : '👩‍⚕️',
    astronaut : '👨‍🚀',
    astronautw : '👩‍🚀',
    elf : '🧝‍♂️',
    elfw : '🧝‍♀️',
    mage : '🧙‍♂️',
    magew : '🧙‍♀️',
    genie : '🧞‍♂️',
    geniew : '🧞‍♀️',
    fairy : '🧚',
    fairym : '🧚‍♂️',
    vampire : '🧛‍♂️',
    vampirew : '🧛‍♀️',
    zombie : '🧟‍♂️',
    zombiew : '🧟‍♀️',
},

animals : {
    elefant : '🐘',
    rhino : '🦏',
    monkey : '🐒',
    gorilla : '🦍',
    sheep : '🐑',
    ram : '🐏',
    goat : '🐐',
    deer : '🦌',
    camel : '🐪',
    horse : '🐎',
    pig : '🐖',
    cow : '🐄',
    turtle : '🐢',
    rabbit : '🐇',
    squirrel : '🐿️',
    hedgehog : '🦔',
    badger : '🦡',
    mouse : '🐁',
    rat : '🐀',
    cat : '🐈',
    dog : '🐕',
    leopard : '🐆',
    tiger : '🐅',
    snake : '🐍',
    gecko : '🦎',
    crocodile : '🐊',
    dragon : '🐉',
    dinosaur : '🦕',
    't-rex' : '🦖',
    dolphin : '🐬',
    shark : '🦈',
    whale : '🐋',
    whale2 : '🐳',
    fugu : '🐡',
    nemo : '🐟',
    dori : '🐠',
    shrimp : '🦐',
    crab : '🦀',
    lobster : '🦞',
    squid : '🦑',
    octopus : '🐙',
    penguin : '🐧',
    bird : '🐦',
    dove : '🕊️',
    parrot : '🦜',
    eagle : '🦅',
    duck : '🦆',
    swan : '🦢',
    owl : '🦉',
    bat : '🦇',
    turkey : '🦃',
    rooster : '🐓',
    chick : '🐥',
    chick2 : '🐤',
    chick3: '🐣',
    snail : '🐌',
    butterfly : '🦋',
    bee : '🐝',
    ant : '🐜',
    cricket : '🦗',
    bug : '🐛',
    ladybug : '🐞',
    spider : '🕷️',
    scorpion : '🦂',
    microbe : '🦠',
},

plants : {
    leaf : '🍂',
    herb : '🌿',
    maple : '🍁',
    shamrock : '☘️',
    luck : '🍀',
    wheat : '🌾',
    corn : '🌽',
    flower : '🌼',
    sunflower : '🌻',
    rose : '🌹',
    hibiscus : '🌺',
    sakura : '🌸',
    tulip : '🌷',
    tree : '🌳',
    pine : '🌲',
    'palm-tree' : '🌴',
    cactus : '🌵',
    sprout : '🌱',
    mushroom : '🍄',
    nut : '🌰',
},

nature : {
    sun : '☀️',
    moon : '🌕',
    'new-moon' : '🌑',
    'crescent-moon' : '🌙',
    fire : '🔥',
    water : '💧',
    wave : '🌊',
    ice : '❄',
    wind : '💨',
    cloud : '☁️',
    mountain : '⛰️',
    volcano : '🌋',
    rainbow : '🌈',
    comet : '☄️',
    asiania : '🌏',
    americas : '🌎',
    eurafrica : '🌍',
    galaxy : '🌌',
    dna : '🧬',
},

actions : {
    add : '✚',
    remove : '─',
    undo : '↶',
    redo : '↷',
    reload : '⟳',
    sync : '🗘',
    minimize : '🗕',
    restore : '🗗',
    maximize : '🗖',
    close : '⨯',
    copy : '🗇',
    accept : '✔️',
    cancel : '✖️',
    eject : '⏏',
    play : '▶',
    pause : 'Ⅱ',
    'play-pause' : '⏯',
    stop : '■',
    prev : '⏮',
    next : '⏭',
    rec : '⚫',
    'rec-on' : '🔴',
    select : '⛶',
    select2 : '⬚',
},

culture : {
    pommee : '🕂',
    maltese : '✠',
    latin : '✝',
    latin2 : '🕇',
    celtic : '🕈',
    jew : '✡',
    ankh : '☥',
    peace : '☮',
    om : '🕉',
    'ying-yang' : '☯',
    atom : '⚛️',
    comunism : '☭',
    'moon-star' : '☪',
    health : '⛨',
    darpa : '☸',
    diamonds : '❖',
},

music : {
    note : '🎵',
    notes : '🎶',
    sharp : '♯',
    flat : '♭',
    cleff : '🎼',
    'cleff-g' : '𝄞',
    'cleff-f' : '𝄢',
    'cleff-c' : '𝄡',
    guitar : '🎸',
    piano : '🎹',
    violin : '🎻',
    saxophone : '🎷',
    trumpet : '🎺',
    drum : '🥁',
},

astro : {
    aries : '♈',
    tauro : '♉',
    gemini : '♊',
    piscis : '♋',
    leo : '♌',
    virgo : '♍',
    libra : '♎',
    scorpio : '♏',
    sagitarius : '♐',
    capricorn : '♑',
    aquarius : '♒',
    cancer : '♓',
    mercury : '☿️',
    venus : '♀',
    earth : '♁',
    mars : '♂',
    jupiter : '♃',
    saturn : '♄',
    uranus : '♅',
    neptune : '♆',
    pluto : '♇',
    ceres : '⚳',
    pallas : '⚴',
    juno : '⚵',
    vesta : '⚶',
    chiron : '⚷',
},

chess : {
    wqueen : '♔',
    wking : '♕',
    wtower : '♖',
    wbishop : '♗',
    whorse : '♘',
    wpawn : '♙',
    bqueen : '♚',
    bking : '♛',
    btower : '♜',
    bbishop : '♝',
    bhorse : '♞',
    bpawn : '♟',
},

arrows : {
    /*
    ↑ ↓ ← → 
    ⬅ ➡ ⬆ ⬇
    ⇦ ⇨ ⇧ ⇩ 
    ◀ ▶ ▲ ▼ 
    ◁ ▷ △ ▽ 
    ↶ ↷
    */
},

keys : {
    command : '⌘',
    option : '⌥',
    shift : '⇧',
    'caps-lock' : '⇪',
    backspace : '⌫',
    return : '⏎',
    enter : '⎆',
    escape : '⎋',
    tab : '↹',
},

geometric : {
    triangle : '▲',
    square : '■',
    pentagon : '⬟',
    hexagon : '⬢',
    circle : '●',
    'curved-triangle' : '🛆',
    'curved-square' : '▢',
    'square-quadrant' : '◰',
    'round-quadrant' : '◴',
    contrast : '◐',
    contrast2 : '◧',
    contrast3 : '◩',
},

hieroglyph : {
    'an-eye' : '𓁹',
    'tear-eye' : '𓂀',
    'an-ear' : '𓂈',
    'writing-arm' : '𓃈',
    'a-leg' : '𓂾',
    'watering-leg' : '𓃂',
    'closed-hand' : '𓂧',
    'open-hand' : '𓂩',
    'a-finger' : '𓂭',
    'crying-blank-eye' : '𓂍',
    'arms-hat-spear' : '𓂙',
    'a-staff' : '𓋈',
    'a-fan' : '𓇬',
    'a-jar' : '𓄣',
    'a-beetle' : '𓆣',
    'a-wasp' : '𓆤',
    'a-fairy' : '𓋏',
    'sitting-man' : '𓀀',
    'happy-sitting-man' : '𓁏',
    'exited-sitting-man' : '𓁕',
    'sitting-woman' : '𓁑',
    'sitting-bird-man' : '𓁟',
    'sitting-wolf-man' : '𓁢',
    'dancing-man' : '𓀤',
    'broken-arms-man' : '𓀣',
    'upside-down-man' : '𓀡',
    'dead-guy' : '𓀿',
    'three-leg-guy' : '𓁲',
},

other : {
    'thumbs-up' : '👍',
    'thumbs-down' : '👎',
    cool : '🤙',
    metal : '🤘',
    spock : '🖖',
    strong : '💪',
    eye : '👁️',
    ear : '👂',
    brain : '🧠',
    glasses : '👓',
    sunglasses : '🕶️',
    goggles : '🥽',
    ribbon : '🎀',
    backpack : '🎒',
    cart : '🛒',
    poo : '💩',
    heart : '❤️',
    hearts : '💕',
    'broken-heart' : '💔',
    star : '⭐',
    crown : '👑',
    trophy : '🏆',
    diamond : '💎',
    jar : '🏺',
    pill : '💊',
    globe : '🌐',
    voltage : '⚡',
    flag : '⚑',
    film : '🎞️',
    recycle : '♻',
    network : '🖧',
    newbie : '🔰',
    trident : '🔱',
    japan : '🗾',
    fuji : '🗻',
    'tokyo-tower' : '🗼',
    liberty : '🗽',
    die : '🎲',
    palette : '🎨',
    frame : '🖼️',
    'crystal-ball' : '🔮',
    bomb : '💣',
    poison : '☠️',
    bitcoin : '₿',
    bisexual : '⚥',
    pansexual : '⚧',
},

/*

🐼🐻🐺🐮🐷🐭🐹🐰🐱🐶🐵🐴🐯🐲🐨🐸🦄

sports & entertainment
🏄🏃🏂🏇🏊🏀⚽⚾🎾⛷⛸⛵⛵
🎳🎲🎱🎰🎯🎭🎬🎩
🎊🎉🎈🎇🎆🎅🎄🎃🎂🎁

food & drink
🍔🍕🍝🍞🍟🍖🍗🍙🍚🍛🍜🍡🍣🍤
🍲🍱🍰🍮🍬🍫🍪🍩🍨🍧🍦
🍓🍒🍑🍐🍏🍎🍍🍌🍋🍊🍉🍈🍇🍅🍄
🍻🍺🍹🍸🍷🍶🍴🍳

other
🎐🎏🎎🎋🏯
🏰🏭🏬🏫🏪🏩🏨🏧🏦🏥🏣🏢
✋❦

*/

}
