module.exports = {

app : {
    gear : '⚙️',
    user : '👤',
    users : '👥',
    lock : '🔒',
    'open-lock' : '🔓',
    key : '🔑',
    home : '🏠',
    exit : '🚪',
    call : '📞',
    search : '🔍',
    battery : '🔋',
    'power-plug' : '🔌',
    alarm : '🔔',
    'alarm-off' : '🔕',
    'volume-min' : '🔈',
    'volume-mid' : '🔉',
    'volume-max' : '🔊',
    mute : '🔇',
    'brightness-low' : '🔅',
    'brightness-hi' : '🔆',
    warning : '⚠',
    error : '⨂',/*𐌈*/
    ban : '🚫',
    bars : '☰',
    'h-dots' : '⋯',
    'v-dots' : '⋮',
    command : '⌘',
    option : '⌥',
    rows : '𝌆',
    columns : '▥',
    grid : '▦',
    'spaced-grid' : '𝍖',
    'round-grid' : '𐄡',
},

office : {
    file : '📄',
    folder : '📂',
    edit : '✏️',
    pen : '🖊️',
    pen2 : '🖋️',
    paintbrush : '🖌️',
    cut : '✂️',
    copy : '📋',
    attach : '📎',
    link : '🔗',
    ruler : '📏',
    pin : '📌',
    card : '💳',
    label : '🏷️',
    memo : '📝',
    scroll : '📜',
    book : '📕',
    books : '📚',
    bookmark : '🔖',
    'open-book' : '📖',
    notebook : '📓',
    calendar : '📅',
    envelope : '✉️',
    email : '📧',
    mailbox : '📫',
    package : '📦',
    briefcase : '💼',
    newspaper : '📰',
    trash : '🗑️',
},

actions : {
    add : '✚',
    remove : '-',
    sync : '🔄',
    close : '✕',
    accept : '✔',
    cancel : '✘',
    eject : '⏏',
    play : '▶',
    next : '▶',
    back : '◀',
    prev : '◀',
    pause : 'Ⅱ',
    stop : '■',
    rec : '●',
},

electronics : {
    laptop : '💻',
    desktop : '🖥️',
    keyboard : '⌨️',
    'pc-mouse' : '🖱️',
    printer : '🖨️',
    smartphone : '📱',
    telephone : '☎️',
    microphone : '🎤',
    'studio-mic' : '🎙️',
    megaphone : '📣',
    headphones : '🎧',
    camera : '📷',
    'video-camera' : '📹',
    'movie-camera' : '🎥',
    projector : '📽️',
    tv : '📺',
    radio : '📻',
    stereo : '📾',
    gamepad : '🎮',
    joystick : '🕹️',
},

media : {
    cd : '💿',
    floppy : '💾',
    minidisc : '💽',
    tape : '📼',
},

tools : {
    bulb : '💡',
    flashlight : '🔦',
    wrench : '🔧',
    hammer : '🔨',
    bolt : '🔩',
    microscope : '🔬',
    telescope : '🔭',
    antenna : '📡',
    satellite : '🛰️',
    watch : '⌚',
    stopwatch : '⏱️',
    clock : '⏰',
    hourglass : '⌛',
},

vehicles : {
    skate : '🛹',
    scooter : '🛴',
    bicycle : '🚲',
    motorscooter : '🛵',
    motorcycle : '🏍️',
    car : '🚗',
    'race-car' : '🏎️',
    rv : '🚙',
    bus : '🚌',
    minibus : '🚐',
    truck : '🚚',
    ambulance : '🚑',
    'fire-engine' : '🚒',
    metro : '🚇',
    train : '🚄',
    locomotive : '🚂',
    sailboat : '⛵',
    speedboat : '🚤',
    motorboat : '🛥️',
    ferry : '⛴️',
    ship : '🚢',
    plane : '✈️',
    'small-plane': '🛩️',
    helicopter : '🚁',
    rocket : '🚀',
    ufo : '🛸',
},

nature : {
    sun : '☀️',
    moon : '🌕',
    'new-moon' : '🌑',
    'crescent-moon' : '🌙',
    fire : '🔥',
    water : '💧',
    wave : '🌊',
    ice : '❄',
    wind : '💨',
    cloud : '☁️',
    mountain : '⛰️',
    volcano : '🌋',
    rainbow : '🌈',
    comet : '☄️',
    asiania : '🌏',
    americas : '🌎',
    eurafrica : '🌍',
    galaxy : '🌌',
},

plants : {
    leaf : '🍂',
    leaves : '🌿',
    maple : '🍁',
    clover : '☘',
    luck : '🍀',
    weat : '🌾',
    corn : '🌽',
    flower : '🌼',
    sunflower : '🌻',
    rose : '🌹',
    hibiscus : '🌺',
    sakura : '🌸',
    tulip : '🌷',
    tree : '🌳',
    pine : '🌲',
    'palm-tree' : '🌴',
    cactus : '🌵',
    sprout : '🌱',
    nut : '🌰',
},

culture : {
    christian : '✝',
    jew : '✡',
    egipt : '☥',
    peace : '☮',
    'ying-yang' : '☯',
    comunism : '☭',
    'moon-star' : '☪',
    columbus : '✠',
    health : '⛨',
    darpa : '☸',
    diamonds : '❖',
},

music : {
    note : '🎵',
    notes : '🎶',
    cleff : '𝄞',
    cleff2 : '🎼',
    guitar : '🎸',
    piano : '🎹',
    violin : '🎻',
    saxophone : '🎷',
    trumpet : '🎺',
},

faces : {
    robot : '🤖',
    skull : '💀',
    poison : '☠️',
    imp : '👿',
    monster : '👾',
    alien : '👽',
    ghost : '👻',
    goblin : '👺',
    ogre : '👹',
},

zodiac : {
    aries : '♈',
    tauro : '♉',
    gemini : '♊',
    piscis : '♋',
    leo : '♌',
    virgo : '♍',
    libra : '♎',
    scorpio : '♏',
    sagitarius : '♐',
    capricorn : '♑',
    aquarius : '♒',
    cancer : '♓',
},

chess : {
    wqueen : '♔',
    wking : '♕',
    wtower : '♖',
    wbishop : '♗',
    whorse : '♘',
    wpawn : '♙',
    bqueen : '♚',
    bking : '♛',
    btower : '♜',
    bbishop : '♝',
    bhorse : '♞',
    bpawn : '♟',
},

animals : {
    elefant : '🐘',
    monkey : '🐒',
    sheep : '🐑',
    goat : '🐐',
    horse : '🐎',
    snake : '🐍',
    puma : '🐆',
    cow : '🐄',
    rabbit : '🐇',
    mouse : '🐁',
    rat : '🐀',
    cat : '🐈',
    tiger : '🐅',
    dragon : '🐉',
    camel : '🐪',
    turtle : '🐢',
    squirrel : '🐿️',
    dolphin : '🐬',
    whale : '🐋',
    whale2 : '🐳',
    crocodile : '🐊',
    fugu : '🐡',
    dori : '🐠',
    nemo : '🐟',
    octopus : '🐙',
    crab : '🦀',
    penguin : '🐧',
    bird : '🐦',
    dove : '🕊️',
    parrot : '🦜',
    eagle : '🦅',
    duck : '🦆',
    swan : '🦢',
    owl : '🦉',
    bat : '🦇',
    turkey : '🦃',
    rooster : '🐓',
    chick : '🐥',
    chick2 : '🐤',
    chick3: '🐣',
    snail : '🐌',
    butterfly : '🦋',
    bee : '🐝',
    ant : '🐜',
    bug : '🐛',
    ladybug : '🐞',
    spider : '🕷️',
    scorpion : '🦂',
    cricket : '🦗',
},

people : {
    hacker : '👨‍💻',
    hackerw : '👩‍💻',
    artist : '👨‍🎨',
    artistw : '👩‍🎨',
    doctor : '👨‍⚕️',
    doctorw : '👩‍⚕️',
    astronaut : '👨‍🚀',
    astronautw : '👩‍🚀',
    mage : '🧙‍♂️',
    magew : '🧙‍♀️',
    genie : '🧞‍♂️',
    geniew : '🧞‍♀️',
    fairy : '🧚',
    fairym : '🧚‍♂️',
    zombie : '🧟‍♂️',
    zombiew : '🧟‍♀️',

},

other : {
    'thumbs-up' : '👍',
    'thumbs-down' : '👎',
    cool : '🤙',
    metal : '🤘',
    spock : '🖖',
    strong : '💪',
    eye : '👁️',
    ear : '👂',
    glasses : '👓',
    sunglasses : '🕶️',
    poo : '💩',
    heart : '❤️',
    hearts : '💕',
    'broken-heart' : '💔',
    star : '⭐',
    diamond : '💎',
    trophy : '🏆',
    jar : '🏺',
    pill : '💊',
    globe : '🌐',
    voltage : '⚡',
    wheelchair : '♿',
    flag : '⚑',
    pentagon : '⬟',
    hexagon : '⬢',
    cycle : '⟳',
    recycle : '♻',
    newbie : '🔰',
    trident : '🔱',
    anchor : '⚓',
    japan : '🗾',
    fuji : '🗻',
    'tokyo-tower' : '🗼',
    liberty : '🗽',
    die : '🎲',
    bomb : '💣',
    crown : '👑',
    palette : '🎨',
    painting : '🖼️',
    map : '🗺️',
    compass : '🧭',
    ribbon : '🎀',
    'crystal-ball' : '🔮',
},

/*

🐼🐻🐺🐮🐷🐭🐹🐰🐱🐶🐵🐴🐯🐲🐨🐸🦄

sports & entertainment
🏄🏃🏂🏇🏊🏀⚽⚾🎾⛷⛸⛵⛵
🎳🎲🎱🎰🎯🎭🎬🎩
🎊🎉🎈🎇🎆🎅🎄🎃🎂🎁

food & drink
🍔🍕🍝🍞🍟🍖🍗🍙🍚🍛🍜🍡🍣🍤
🍲🍱🍰🍮🍬🍫🍪🍩🍨🍧🍦
🍓🍒🍑🍐🍏🍎🍍🍌🍋🍊🍉🍈🍇🍅🍄
🍻🍺🍹🍸🍷🍶🍴🍳

other
🎐🎏🎎🎋🏯
🏰🏭🏬🏫🏪🏩🏨🏧🏦🏥🏣🏢
✋❦

*/

}
