module.exports = {

app : {
    menu : '☰',
    options : '⋯',
    voptions : '⋮',
    settings : '⚙',
    user : '👤',
    users : '👥',
    lock : '🔒',
    'open-lock' : '🔓',
    key : '🔑',
    home : '🏠',
    exit : '🚪',
    command : '⌘',
    option : '⌥',
    search : '🔍',
    battery : '🔋',
    'power-plug' : '🔌',
    alarm : '🔔',
    'alarm-off' : '🔕',
    'volume-min' : '🔈',
    'volume-mid' : '🔉',
    'volume-max' : '🔊',
    mute : '🔇',
    'brightness-low' : '🔅',
    'brightness-hi' : '🔆',
    warning : '⚠',
    error : '⨂',/*𐌈*/
    nope : '🚫',
    rows : '𝌆',
    columns : '▥',
    grid : '▦',
    'spaced-grid' : '𝍖',
    'round-grid' : '𐄡',
},

office : {
    file : '📄',
    folder : '📂',
    edit : '✎',
    cut : '✂',
    copy : '📋',
    attach : '📎',
    link : '🔗',
    ruler : '📏',
    pin : '📌',
    card : '💳',
    memo : '📝',
    scroll : '📜',
    book : '📕',
    books : '📚',
    bookmark : '🔖',
    'open-book' : '📖',
    notebook : '📓',
    calendar : '📅',
    email : '📧',
    mailbox : '📫',
    package : '📦',
    briefcase : '💼',
    newspaper : '📰',
},

actions : {
    add : '✚',
    remove : '-',
    update : '🔄',
    close : '✕',
    accept : '✔',
    cancel : '✘',
    eject : '⏏',
    play : '▶',
    next : '▶',
    back : '◀',
    prev : '◀',
    pause : 'Ⅱ',
    stop : '■',
    rec : '●',
},

electronics : {
    computer : '💻',
    keyboard : '⌨',
    smartphone : '📱',
    telephone : '📞',
    microphone : '🎤',
    megaphone : '📣',
    headphones : '🎧',
    camera : '📷',
    videocamera : '📹',
    tv : '📺',
    radio : '📻',
    stereo : '📾',
    gamepad : '🎮',
    joystick : '🎮',
},

media : {
    cd : '💿',
    floppy : '💾',
    minidisc : '💽',
    tape : '📼',
},

tools : {
    bulb : '💡',
    flashlight : '🔦',
    wrench : '🔧',
    hammer : '🔨',
    bolt : '🔩',
    glasses : '👓',
    microscope : '🔬',
    telescope : '🔭',
    antenna : '📡',
    watch : '⌚',
    timer : '⏱',
    clock : '⏰',
    hourglass : '⌛',
},

vehicles : {
    bicycle : '🚲',
    car : '🚗',
    bus : '🚌',
    truck : '🚚',
    metro : '🚇',
    train : '🚄',
    locomotive : '🚂',
    ship : '🚢',
    plane : '✈',
    helicopter : '🚁',
    rocket : '🚀',
},

nature : {
    fire : '🔥',
    water : '💧',
    wave : '🌊',
    ice : '❄',
    wind : '💨',
    volcano : '🌋',
    rainbow : '🌈',
    asiania : '🌏',
    americas : '🌎',
    eurafrica : '🌍',
},

plants : {
    leaf : '🍂',
    leaves : '🌿',
    oak : '🍁',
    clover : '☘',
    luck : '🍀',
    weat : '🌾',
    corn : '🌽',
    flower : '🌼',
    sunflower : '🌻',
    rose : '🌹',
    hibiscus : '🌺',
    sakura : '🌸',
    tulip : '🌷',
    tree : '🌳',
    pine : '🌲',
    'palm-tree' : '🌴',
    cactus : '🌵',
    sprout : '🌱',
    nut : '🌰',
},

culture : {
    christian : '✝',
    jew : '✡',
    egipt : '☥',
    peace : '☮',
    'ying-yang' : '☯',
    comunism : '☭',
    'moon-star' : '☪',
    columbus : '✠',
    health : '⛨',
    darpa : '☸',
    diamonds : '❖',
},

music : {
    note : '🎵',
    notes : '🎶',
    cleff : '𝄞',
    cleff2 : '🎼',
    guitar : '🎸',
    piano : '🎹',
    violin : '🎻',
    saxophone : '🎷',
    trumpet : '🎺',
},

faces : {
    skull : '💀',
    poison : '☠',
    imp : '👿',
    monster : '👾',
    alien : '👽',
    ghost : '👻',
    goblin : '👺',
    ogre : '👹',
},

zodiac : {
    aries : '♈',
    tauro : '♉',
    gemini : '♊',
    piscis : '♋',
    leo : '♌',
    virgo : '♍',
    libra : '♎',
    scorpio : '♏',
    sagitarius : '♐',
    capricorn : '♑',
    aquarius : '♒',
    cancer : '♓',
},

chess : {
    wqueen : '♔',
    wking : '♕',
    wtower : '♖',
    wbishop : '♗',
    whorse : '♘',
    wpawn : '♙',
    bqueen : '♚',
    bking : '♛',
    btower : '♜',
    bbishop : '♝',
    bhorse : '♞',
    bpawn : '♟',
},

other : {
    good : '👍',
    bad : '👎',
    strong : '💪',
    poo : '💩',
    shit : '💩',
    love : '❤',
    heart : '❤',
    hearts : '💕',
    'broken-heart' : '💔',
    star : '★',
    goldstar : '⭐',
    diamond : '💎',
    pill : '💊',
    globe : '🌐',
    voltage : '⚡',
    wheelchair : '♿',
    flag : '⚑',
    pentagon : '⬟',
    hexagon : '⬢',
    cycle : '⟳',
    recycle : '♻',
    newbie : '🔰',
    trident : '🔱',
    japan : '🗾',
    fuji : '🗻',
    'tokyo-tower' : '🗼',
    liberty : '🗽',
    bomb : '💣',
    crown : '👑',
    palette : '🎨',
    ribbon : '🎀',
    'crystal-ball' : '🔮',
    hal : '🔘',
},


animals : {
    elefant : '🐘',
    monkey : '🐒',
    sheep : '🐑',
    goat : '🐐',
    horse : '🐎',
    snake : '🐍',
    puma : '🐆',
    cow : '🐄',
    rabbit : '🐇',
    mouse : '🐁',
    rat : '🐀',
    cat : '🐈',
    tiger : '🐅',
    dragon : '🐉',
    camel : '🐪',
    turtle : '🐢',
    dolphin : '🐬',
    whale : '🐋',
    whale2 : '🐳',
    crocodile : '🐊',
    fugu : '🐡',
    dori : '🐠',
    nemo : '🐟',
    octopus : '🐙',
    penguin : '🐧',
    pidgeon : '🐦',
    bird : '🐥',
    bird2 : '🐤',
    bird3: '🐣',
    snail : '🐌',
    bee : '🐝',
    ant : '🐜',
    bug : '🐛',
    ladybug : '🐞',
},

/*

🐼🐻🐺🐮🐷🐭🐹🐰🐱🐶🐵🐴🐯🐲🐨🐸

sports & entertainment
🏆🏄🏃🏂🏇🏊🏀⚽⚾🎾⛷⛸⛵⛵
🎳🎲🎱🎰🎯🎭🎬🎩
🎊🎉🎈🎇🎆🎅🎄🎃🎂🎁

food & drink
🍔🍕🍝🍞🍟🍖🍗🍙🍚🍛🍜🍡🍣🍤
🍲🍱🍰🍮🍬🍫🍪🍩🍨🍧🍦
🍓🍒🍑🍐🍏🍎🍍🍌🍋🍊🍉🍈🍇🍅🍄
🍻🍺🍹🍸🍷🍶🍴🍳

other
🎐🎏🎎🎋🏯
🏰🏭🏬🏫🏪🏩🏨🏧🏦🏥🏣🏢
✋❦

*/

}
